# Rust edition (2015, 2018, 2021, or 2024)
edition = "2024"

# Maximum line length before wrapping
max_width = 100

# Number of spaces per indentation level
tab_spaces = 4

# Use tabs instead of spaces for indentation
hard_tabs = false

# Sort import statements alphabetically
reorder_imports = true

# Sort module declarations alphabetically
reorder_modules = true

# Line ending style ("Unix" for LF, "Windows" for CRLF, "Native" for OS default)
newline_style = "Unix"

# Use field init shorthand (field instead of field: field)
use_field_init_shorthand = true

# Use ? operator instead of try! macro
use_try_shorthand = true

# Remove unnecessary nested parentheses
remove_nested_parens = true

# Maximum width for method chains before breaking
chain_width = 60

# Controls when to break expressions into multiple lines ("Default", "Max", or "Off")
use_small_heuristics = "Default"
